config/routes.rb
Rails.application.routes.draw do
  get 'message/:id' => "messages#show", as: "message"
  delete 'message/:id' => "messages#destroy"
  resources :messages, only: [:create]

  devise_for :users
  resources :users,only: [:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "confirm"
  end
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  get 'finder' => "finders#finder"
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
 belongs_to :user
 belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
 belongs_to :user
 belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
	validates :body, presence: true
  validates :draft, presence: true

	has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_images, dependent: :destroy
  accepts_attachments_for :post_images, attachment: :image

  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_one :spot, dependent: :destroy
  accepts_nested_attributes_for :spot




  def self.looks(searches, words)
    if searches == "perfect_match"
      @post = Post.where("title LIKE ?", "#{words}")
    else
      @post = Post.where("title LIKE ?", "%#{words}%")
    end
  end


  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_post_tag
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  enum draft: { published: 0, draft: 1 }

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :post
  attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"


end

app/models/room.rb
class Room < ApplicationRecord
 has_many :messages
 has_many :entries

end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :post

  geocoded_by :address
  after_validation :geocode
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :tag_maps

  def self.looks(searches, words)
    if searches == "perfect_match"
      @tag = Tag.where("tag_name LIKE ?", "#{words}")
    else
      @tag = Tag.where("tag_name LIKE ?", "%#{words}%")
    end
  end

end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :post_id, presence: true
  validates :tag_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :relationships, class_name: "Relationship",
                           foreign_key: "follower_id",
                           dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship",
                                      foreign_key: "followed_id",
                                      dependent: :destroy
  has_many :followings,   through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  has_many :entries
  has_many :messages
  has_many :rooms, through: :user_rooms

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 100}

  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    else
      @user = User.where("name LIKE ?", "%#{words}%")
    end
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_id = @post.id
    comment.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    PostComment.find_by(id: params[:id], post_id: params[:post_id]).destroy
  end



  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/finders_helper.rb
module FindersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/post_comments/_comment_count.html.erb
<i class="fas fa-comment"><%= post.post_comments.count %></i>

app/views/post_comments/_comment_index.html.erb
<div class="widget-area no-padding blank">
  <div class="row">
    <div class="col-sm-12">
      <h3 style="margin: 20px 0;">コメント一覧</h3>
    </div><!-- /col-sm-12 -->
  </div><!-- /row -->
  <% post.post_comments.each do |post_comment| %>
  <div class="row">
    <div class="col-sm-1">
      <div class="thumbnail">
        <p><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></p>
      </div><!-- /thumbnail -->
    </div><!-- /col-sm-1 -->
    <div class="col-sm-11">
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong><%= post_comment.user.name %></strong>
          <span class="text-muted"><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
          <% if post_comment.user == current_user %>
            <span><%= link_to "削除", post_post_comment_path(post.id, post_comment.id), method: :delete, remote: true %></span>
          <% end %>
        </div>
        <div class="panel-body">
          <%= post_comment.comment %>
        </div><!-- /panel-body -->
      </div><!-- /panel panel-default -->
    </div><!-- /col-sm-5 -->
  </div>
  <% end %>
</div>

app/views/post_comments/create.js.erb
$(".post_comment").html("<%= j(render 'post_comments/comment_index', post: @post, user: @user) %>");
$("textarea").val("");
$(".comment_count").html("<%= j(render 'post_comments/comment_count', post: @post ) %>")

app/views/post_comments/destroy.js.erb
$(".post_comment").html("<%= j(render 'post_comments/comment_index',  post: @post, user: @user) %>");
$(".comment_count").html("<%= j(render 'post_comments/comment_count', post: @post ) %>");