config/routes.rb
Rails.application.routes.draw do
  get 'message/:id' => "messages#show", as: "message"
  delete 'message/:id' => "messages#destroy"
  resources :messages, only: [:create]

  devise_for :users
  resources :users,only: [:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "confirm"
  end
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  get 'finder' => "finders#finder"
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
 belongs_to :user
 belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
 belongs_to :user
 belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
	validates :body, presence: true
  validates :draft, presence: true

	has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_images, dependent: :destroy
  accepts_attachments_for :post_images, attachment: :image

  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_one :spot, dependent: :destroy
  accepts_nested_attributes_for :spot




  def self.looks(searches, words)
    if searches == "perfect_match"
      @post = Post.where("title LIKE ?", "#{words}")
    else
      @post = Post.where("title LIKE ?", "%#{words}%")
    end
  end


  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_post_tag
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  enum draft: { published: 0, draft: 1 }

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :post
  attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"


end

app/models/room.rb
class Room < ApplicationRecord
 has_many :messages
 has_many :entries

end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :post

  geocoded_by :address
  after_validation :geocode
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :tag_maps

  def self.looks(searches, words)
    if searches == "perfect_match"
      @tag = Tag.where("tag_name LIKE ?", "#{words}")
    else
      @tag = Tag.where("tag_name LIKE ?", "%#{words}%")
    end
  end

end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :post_id, presence: true
  validates :tag_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :relationships, class_name: "Relationship",
                           foreign_key: "follower_id",
                           dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship",
                                      foreign_key: "followed_id",
                                      dependent: :destroy
  has_many :followings,   through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  has_many :entries
  has_many :messages
  has_many :rooms, through: :user_rooms

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 100}

  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    else
      @user = User.where("name LIKE ?", "%#{words}%")
    end
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.published.order("created_at DESC").page(params[:page]).per(4)
    if params[:tag_id] != nil
      @posts = Post.published.order("created_at DESC").page(params[:page]).per(4)
      @tag = Tag.find(params[:tag_id])
      @tag_posts = @tag.posts.all
    end
    # draft の post に紐づく tag は表示しない
    @tag_list = @posts.flat_map { |post| post.tags }.compact.uniq
  end

  def show
    @post = Post.find(params[:id])
      if @post.draft == "draft"
        redirect_to root_path notice: "こちらの記事は非公開になります"
      end
    @user = @post.user
    @post_comment = PostComment.new
    @post_tags = @post.tags
    @lat = @post.spot.latitude
    @lng = @post.spot.longitude
    gon.lat = @lat
    gon.lng = @lng
  end

  def new
    @post = Post.new
    @post.build_spot
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      save_tag
      redirect_to post_path(@post), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      save_tag
      redirect_to posts_path, notice: "You have created post successfully."
    else
      @post = Post.new
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title,:body,:draft,:latitude,:longitude,post_images_images: [], spot_attributes: [:address])
  end

  def save_tag
    tag_list = params[:post][:tag_name].split(nil)
    @post.save_tag(tag_list)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :ensure_correct_user, only: [:edit,:update]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(4)
  end

  def index
    @users = User.all
  end

  def confirm
    @user = User.find(params[:user_id])
    @posts = @user.posts.draft.order("created_at DESC").page(params[:page]).per(4)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/finders_helper.rb
module FindersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_comment_index.html.erb
<div class="widget-area no-padding blank">
  <div class="row">
    <div class="col-sm-12">
      <h3 style="margin: 20px 0;">コメント一覧</h3>
    </div><!-- /col-sm-12 -->
  </div><!-- /row -->
  <% post.post_comments.each do |post_comment| %>
  <div class="row">
    <div class="col-sm-1">
      <div class="thumbnail">
        <p><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></p>
      </div><!-- /thumbnail -->
    </div><!-- /col-sm-1 -->
    <div class="col-sm-11">
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong><%= post_comment.user.name %></strong>
          <span class="text-muted"><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
          <% if post_comment.user == current_user %>
            <span><%= link_to "削除", post_post_comments_path(post.id, post_comment.id), method: :delete %></span>
          <% end %>
        </div>
        <div class="panel-body">
          <%= post_comment.comment %>
        </div><!-- /panel-body -->
      </div><!-- /panel panel-default -->
    </div><!-- /col-sm-5 -->
    </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with model:post,local:true do |f| %>
  <div class="form-group" style="margin-top: 10px;">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.fields_for :spot do |s| %>
      <div><%= s.label :address, "レビュー場所(Google Mapで検索)", class: 'spot__title' %></div>
      <%= s.text_field :address, placeholder: "スポットを入力", id: "address", class: 'form-control' %>
    <% end %>
  </div>
   <div class="form-group">
    <%= f.label :image %>
    <%= f.attachment_field :post_images_images, multiple: true, class: "form-control-file post_image" %>
    </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :タグ %>
    <%= f.text_area :tag_name, value: @post.tags.map(&:tag_name).join(' '), class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :公開ステータス %>
    <%= f.select :draft, Post.drafts.keys.map { |k| [t("enums.post.draft.#{k}"),k]} %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/posts/_index.html.erb
<% posts.each do |post| %>
    <div class="card-box">
      <div class="cardbox-heading">
        <div class="media m-0">
		      <div class="d-flex mr-3">
				    <%= attachment_image_tag(post.user, :profile_image,:fill,50,50, fallback: "no_image.jpg", size: "50x50") %>
			    </div>
		      <div class="media-body">
			      <p style="line-height: 50px;">
			        <%= link_to user_path(post.user) do %>
			          <%= post.user.name %>
		          <% end %>
			      </p>
			    </div>
		    </div><!--/ media -->
		    <div class="cardbox-item">
		      <% if post.post_images.present? %>
            <% post.post_images.first(1).each do |post_image| %>
              <p><%= attachment_image_tag(post_image, :image,:fill,300,300, fallback: "no_image.jpg", size: "300x300", class: "cardbox-item") %></p>
            <% end %>
          <% else %>
            画像はありません。
          <% end %>
		    </div>
		    <div class="cardbox-base" style="margin-top: 20px;">
		      <h3>
		        <%= link_to post_path(post) do %>
		          <%= post.title %>
		        <% end %>
		      </h3>
		      <p style="margin-top: 10px:"><%= post.spot.address %></p>
		      <p class="favorite-count" style="margin-top: 10px:"><%= render 'favorites/favorites_count', post: post %></p>
		    </div>
		    <div class="row float-right">
			    <div class="footer" style="margin-top: 5px;">
  			    <p>
  			      <span class="fas fa-tag">Tags:</span>
  						<% post.tags.each do |tag| %>
			        	<span><%= link_to tag.tag_name,posts_path(tag_id: tag.id) %></span>
  						<% end %>
    			    <span>|</span>
          	  <span id="favorite-<%= post.id %>"><%= render 'favorites/favorites_form', post: post %></span>
              <span>|</span>
              <span class="comment_count">
              	<%= link_to post_path(post) do %>
              		<i class="fas fa-comment">
              			<%= post.post_comments.count %>
              		</i>
              		<% end %>
              </span>
              <span>|</span>
              <span><%= post.created_at.strftime('%Y/%m/%d') %></span>
            </p>
          </div>
        </div>
	    </div><!--/ cardbox-heading -->
    </div>
<% end %>

app/views/posts/_rightbar.html.erb
<div class="card-box" style="margin-top: 30px;">
  <h5 style="margin-bottom: 20px;">サイト内検索</h5>
  <div class="form-group">
    <%= form_with url: finder_path, method: :get, local: :true do |f| %>
      <span><%= f.select :range, options_for_select([['User'], ['Post'], ['Tag']]) %></span>
      <%= f.hidden_field :search, "部分一致" => "partial_match" %>
      <span><%= f.text_field :word, size: "18" %></span>
      <span><%= f.submit "検索" %></span>
    <% end %>
  </div>
</div>
<div class="card-box" style="margin-top: 30px;">
  <h5 style="margin-bottom: 20px;">タグ一覧</h5>
  <ul>
    <li>
      <%= link_to "すべて", posts_path()  %>
    </li>
  <% tag_list.each do |list| %>
    <li>
      <%= link_to list.tag_name, posts_path(tag_id: list.id)  %>
      <%= "(#{list.posts.count})" %>
    </li>
  <% end %>
  </ul>
</div>

app/views/posts/_tagbar.html.erb
<div class="card-box" style="margin-top: 30px;">
  <h5 style="margin-bottom: 20px;">タグ一覧</h5>
  <ul>
    <li>
      <%= link_to "すべて", posts_path()  %>
    </li>
  <% tag_list.each do |list| %>
    <li>
      <%= link_to list.tag_name, posts_path(tag_id: list.id)  %>
      <%= "(#{list.posts.count})" %>
    </li>
  <% end %>
  </ul>
</div>

app/views/posts/edit.html.erb
<%= render 'layouts/menubar' %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'users/leftbar', user: current_user %>
    </div>
    <div class='col-md-6'>
       <h1 style="margin-top: 30px;">投稿編集</h1>
      <%= render "form", post: @post  %>
    </div>
    <div class='col-md-3'>
      <%= render 'finders/searchbar' %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'layouts/about' %>
<%= render 'layouts/menubar' %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3 border-right'>
      <%= render 'users/leftbar', user: current_user %>
    </div>
    <div class='col-md-6'>
      <% if @tag != nil %>
        <%= "タグが" + strong= "#{@tag.tag_name}" + "の投稿一覧" %>
        <%= render "index", posts: @tag_posts %>
      <% else %>
        <%= render "index", posts: @posts %>
      <% end %>
    </div>
    <div class='col-md-3 border-left'>
      <%= render 'finders/searchbar' %>
      <%= render 'posts/tagbar', tag_list: @tag_list %>
    </div>
  </div>
  <div class="row d-flex align-items-center justify-content-center">
    <div class="pagination" style= "margin: 10px;"><%= paginate @posts %></div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'layouts/menubar' %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3 border-right'>
      <%= render 'users/leftbar', user: current_user %>
    </div>
    <div class='col-md-6'>
      <h1 style="margin-top: 30px;">新規投稿</h1>
      <%= render 'form', post: @post %>
    </div>
    <div class='col-md-3 border-left'>
      <%= render 'finders/searchbar' %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= render 'layouts/menubar' %>
<div class="container">
	<div class="card-box">
				<div class="container-fliud">
				<div class="wrapper row">
					<div class="slider-show" style="height: 450px; width: 450px; margin:0 30px;">
						<% if @post.post_images.present? %>
            	<% @post.post_images.each do |post_image| %>
              	<div style="height: 450px; width: 450px;"><%= attachment_image_tag(post_image, :image,:fill,450,450, fallback: "no_image.jpg", size: "320x420", class: "cardbox-item") %></div>
              <% end %>
            <% end %>
            <div id="show_map", style="height: 450px; width: 450px;"></div>
					</div>
					<div class="details col-md-6">
						<h1 style="margin: 20px 0 5px 0;"><%= @post.title %></h1>
						<p style="margin-bottom: 10px;"><%= @post.spot.address %></p>
						<p class="favorite-count" style="margin-bottom: 20px:"><%= render 'favorites/favorites_count', post: @post %></p>
						<p><%= @post.body %></p>
					</div>
				</div>
			</div>
			<div class="row float-right">
			  <div class="footer" style="margin-top: 5px;">
  			  <p>
  			    <span>Tags:</span>
  			    <% @post_tags.each do |tag| %>
  			      <span><%= link_to tag.tag_name,posts_path(tag_id: tag.id) %></span>
  			    <% end %>
  			    <span>|</span>
        	  <span id="favorite-<%= @post.id %>"><%= render 'favorites/favorites_form', post: @post %></span>
            <span>|</span>
            <span class="comment_count"><%= render 'post_comments/comment_count', post: @post %></span>
            <span>|</span>
            <span><%= @post.created_at.strftime('%Y/%m/%d') %></span>
            <% if current_user == @user %>
              <span>|</span>
              <span><%= link_to '編集', edit_post_path(@post.id), class: "btn btn-sm btn-success" %></span>
              <span>|</span>
              <span><%= link_to '削除', post_path(@post.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></span>
            <% end %>
          </p>
        </div>
      </div>
		</div>
	<div class="post_comment"><%= render 'post_comments/comment_index', post: @post, user: @user %></div>
	<div class="row">
  	<div class="col-md-12">
 			 <%= form_with(model:[@post, @post_comment]) do |f| %>
    		<div class="widget-area no-padding blank">
      		<div class="status-upload">
        		<p><%= f.text_area :comment, placeholder: "コメントをここに", class: "form" %></p>
        		<p class="button"><%= f.submit "送信する", class: "btn btn-success green" %></p>
      		</div>
    		</div>
  		<% end %>
  	</div>
	</div>
</div>

app/views/users/_info.html.erb
<% if user_signed_in? %>
  <table class='table'>
    <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
    <tr>
	    <th>name</th>
	    <th><%= user.name %></th>
    </tr>
    <tr>
	    <th>introduction</th>
	    <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>
        <% user ||= current_user %>
          <a href="<%= user_followings_path(user) %>">
            <strong id="following" class="stat">
              <%= user.followings.count %>
            </strong>
            following
          </a>
      </th>
      <th>
        <a href="<%= user_followers_path(user) %>">
          <strong id="followers" class="stat">
            <%= user.followers.count %>
          </strong>
          followers
        </a>
      </th>
    </tr>
    <tr>
      <% if current_user != user %>
      <% if current_user.following?(user) %>
        <th><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %></th>
      <% else %>
        <th><%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %></th>
      <% end %>
      <% end %>
    </tr>
    <tr>
      <% if current_user == user %>
        <th><%= link_to '下書き', user_confirm_path(user.id), class: "btn btn-sm btn-success" %></th>
      <% else %>
      <% end %>
    </tr>
    <tr>
      <% if current_user != user %>
        <%= link_to 'チャットする', message_path(user.id) %>
      <% end %>
    </tr>
  </table>
  <div class='row'>
    <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
  </div>
<% else %>
<% end %>

app/views/users/_leftbar.html.erb
<% if user_signed_in? %>
<div class="card-box" style="margin-top: 30px;">
  <div class="profile-userpic">
		<%= attachment_image_tag(user, :profile_image, :fill, 300, 300, fallback: "no_image.jpg", size: '100x100', class: "rounded-circle") %>
	</div>
	<div class="profile-usertitle">
  	<div class="profile-usertitle-name"><%= user.name %></div>
	</div>
	<div class="profile-userbuttons">
		<span style="padding-right: 10px;">
        <a href="<%= user_followings_path(user) %>">
          <%= user.followings.count %>
          フォロー
        </a>
    </span>
    <span>
      <a href="<%= user_followers_path(user) %>">
        <%= user.followers.count %>
        フォロワー
      </a>
    </span>
	</div>
  <div class="profile-usermenu">
		<ul class="nav">
			<li><%= link_to '下書き一覧', user_confirm_path(user.id), class: "btn btn-block" %></li>
			<li> <%= link_to 'ユーザー情報編集',edit_user_path(user),class: "btn btn-block" %></li>
		</ul>
	</div>
</div>
<% end %>

app/views/users/confirm.html.erb
<%= render 'layouts/menubar' %>
<% @posts.each do |post| %>
  <% post.tags.each do |tag| %>
    <div class="card-box">
      <div class="cardbox-heading">
		    <div class="cardbox-base" style="margin-top: 20px;">
		      <h3>
		        <%= link_to edit_post_path(post) do %>
		          <%= post.title %>
		        <% end %>
		      </h3>
		    </div>
		    <div class="row float-right">
			    <div class="footer" style="margin-top: 5px;">
  			    <p>
  			      <span>Tags:</span>
			        <span><%= link_to tag.tag_name,posts_path(tag_id: tag.id) %></span>
            </p>
          </div>
        </div>
	    </div><!--/ cardbox-heading -->
    </div>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<%= render 'layouts/menubar' %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3 border-right'>
      <%= render 'users/leftbar', user: current_user %>
    </div>
    <div class='col-md-6'>
      <h2 style="margin-top: 30px;">ユーザー情報編集</h2>
      <%= form_with model:@user, local:true do |f| %>
        <%= render 'layouts/errors', obj: @user %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
    <div class='col-md-3 border-left'>
      <%= render 'finders/searchbar' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<%= render 'layouts/menubar' %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3 border-right'>
      <%= render 'leftbar', user: current_user %>
    </div>
    <div class='col-md-6'>
      <div class="row" style="margin-top: 30px;">
        <div class="col-md-6 img">
          <%= attachment_image_tag(@user, :profile_image, :fill, 208, 208, fallback: "no_image.jpg") %>
        </div>
        <div class="col-md-6 details">
          <div>
            <span style="font-size: 20px;"><%= @user.name %></span>
            <span style="margin-left: 10px; line-height: 10px;">
              <% if current_user != @user %>
                <% if current_user.following?(@user) %>
                  <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(@user.id), method: :post %>
                <% end %>
              <% end %>
            </span>
            <span style="margin-left: 5px; line-height: 10px;">
              <% if current_user != @user %>
                <%= link_to 'チャットする', message_path(@user.id) %>
              <% end %>
            </span>
          </div>
          <div style="margin-top: 10px;">
            <small>
              <span style="padding-right: 10px;">
                <a href="<%= user_followings_path(@user) %>">
                  <%= @user.followings.count %>
                  フォロー
                </a>
              </span>
              <span>
                <a href="<%= user_followers_path(@user) %>">
                  <%= @user.followers.count %>
                  フォロワー
                </a>
              </span>
            </small>
          </div>
          <p><%= @user.introduction %></p>
        </div>
      </div>
      <% @posts.each do |post| %>
          <div class="card-box">
            <div class="cardbox-heading">
      		    <div class="cardbox-item">
      		      <% if post.post_images.present? %>
                  <% post.post_images.first(1).each do |post_image| %>
                    <p><%= attachment_image_tag(post_image, :image,:fill,300,300, fallback: "no_image.jpg", size: "300x300", class: "cardbox-item") %></p>
                  <% end %>
                <% else %>
                  画像はありません。
                <% end %>
      		    </div>
      		    <div class="cardbox-base" style="margin-top: 20px;">
      		      <%= link_to post_path(post) do %>
      		      <h3><%= post.title %></h3>
      		      <% end %>
      		      <p style="margin-top: 10px:"><%= post.spot.address %></p>
      		    </div>
      		    <div class="row float-right">
      			    <div class="footer" style="margin-top: 5px;">
        			    <p>
        			      <span>Tags:</span>
      			        <span>
                      <% post.tags.each do |tag| %>
      			            <%= link_to tag.tag_name,posts_path(tag_id: tag.id) %>
      			          <% end %>
      			        </span>
          			    <span>|</span>
                	  <span id="favorite-<%= post.id %>"><%= render 'favorites/favorites_form', post: post %></span>
                    <span>|</span>
                    <span class="comment_count"><%= post.post_comments.count %></span>
                    <span>|</span>
                    <span><%= post.created_at.strftime('%Y/%m/%d') %></span>
                    <% if current_user == @user %>
                      <span>|</span>
                      <span><%= link_to '編集', edit_post_path(post.id), class: "btn btn-sm btn-success" %></span>
                      <span>|</span>
                      <%= link_to '削除', post_path(post.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%>
                    <% end %>
                  </p>
                </div>
              </div>
      	    </div><!--/ cardbox-heading -->
          </div>
      <% end %>
    </div>
    <div class='col-md-3 border-left'>
      <%= render 'finders/searchbar' %>
    </div>
  </div>
  <div class="row d-flex align-items-center justify-content-center">
    <div style= "margin: 10px;"><%= paginate @posts %></div>
  </div>
</div>