config/routes.rb
Rails.application.routes.draw do
  get 'message/:id' => "messages#show", as: "message"
  delete 'message/:id' => "messages#destroy"
  resources :messages, only: [:create]

  devise_for :users
  resources :users,only: [:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "confirm"
  end
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  get 'finder' => "finders#finder"
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
 belongs_to :user
 belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
 belongs_to :user
 belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
	validates :body, presence: true
  validates :draft, presence: true

	has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_images, dependent: :destroy
  accepts_attachments_for :post_images, attachment: :image

  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_one :spot, dependent: :destroy
  accepts_nested_attributes_for :spot




  def self.looks(searches, words)
    if searches == "perfect_match"
      @post = Post.where("title LIKE ?", "#{words}")
    else
      @post = Post.where("title LIKE ?", "%#{words}%")
    end
  end


  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_post_tag
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  enum draft: { published: 0, draft: 1 }

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :post
  attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"


end

app/models/room.rb
class Room < ApplicationRecord
 has_many :messages
 has_many :entries

end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :post

  geocoded_by :address
  after_validation :geocode
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :tag_maps

  def self.looks(searches, words)
    if searches == "perfect_match"
      @tag = Tag.where("tag_name LIKE ?", "#{words}")
    else
      @tag = Tag.where("tag_name LIKE ?", "%#{words}%")
    end
  end

end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :post_id, presence: true
  validates :tag_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :relationships, class_name: "Relationship",
                           foreign_key: "follower_id",
                           dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship",
                                      foreign_key: "followed_id",
                                      dependent: :destroy
  has_many :followings,   through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  has_many :entries
  has_many :messages
  has_many :rooms, through: :user_rooms

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 100}

  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    else
      @user = User.where("name LIKE ?", "%#{words}%")
    end
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/finders_helper.rb
module FindersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_about.html.erb
<%# About,画像スライダー部分 %>
<div class="title-box about h-100 w-100">
  <div class="slider h-100 w-100">
    <div class="about-box d-flex align-items-center justify-content-center">
      <%= image_tag 'AboutTravel.jpg', class: "slider-image" %>
    </div>
    <div class="about-box d-flex align-items-center justify-content-center">
      <%= image_tag 'AboutBook.jpg', class: "slider-image" %>
    </div>
    <div class="about-box d-flex align-items-center justify-content-center">
      <%= image_tag 'AboutMusic.jpg', class: "slider-image" %>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_menubar.html.erb
<div class="title-box">
  <ul class="nav menu justify-content-center border" style="padding: 20px;">
    <% if user_signed_in? %>
      <li class="nav-item" style="margin-right: 20px;">
        <%= link_to "Home", posts_path, class: "nav-btn" %>
      </li>
      <li class="nav-item" style="margin-right: 20px;">
        <%= link_to "新規投稿", new_post_path, class: "nav-btn" %>
      </li>
      <li class="nav-item" style="margin-right: 20px;">
        <%= link_to "マイページ", user_path(current_user), class: "nav-btn" %>
      </li>
      <li class="nav-item" style="margin-right: 20px;">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-btn" %>
      </li>
    <% else %>
      <li class="nav-item" style="margin-right: 20px;">
        <%= link_to "Home", posts_path, class: "nav-btn" %>
      </li>
      <li class="nav-item" style="margin-right: 20px;">
        <%= link_to "新規登録", new_user_registration_path, class: "nav-btn" %>
      </li>
      <li class="nav-item">
        <%= link_to "ログイン", new_user_session_path, class: "nav-btn" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Motonetatravel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= include_gon %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# slickの導入 %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <div class="container">
      <%# titlelogo部分 %>
      <div class="title-box d-flex align-items-center justify-content-center">
        <div class="title-logo"></div>
      </div>
      <%= yield %>
      <footer class="p-5 text-center border-top">
      <p class="mt-3">©All rights reserved by Motoneta Travel</p>
      </footer>
      <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_MAP_KEY"] %>&callback=initMap" type="text/javascript"></script>
      <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js" type="text/javascript"></script>
      <script src="//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" type="text/javascript"></script>
    </div>
  </body>
</html>